/* GENERATED by radio/phy_config.py - do not edit by hand. */
#ifndef NRF24_CONFIG_H
#define NRF24_CONFIG_H

#include <stdint.h>

typedef struct { uint8_t addr; uint8_t value; } nrf24_reg_t;

typedef struct {
    const char *name;
    const nrf24_reg_t *regs;  /* CONFIG last: it powers the radio up */
    uint8_t n_regs;
    uint8_t rf_ch;            /* f = 2400 + rf_ch MHz */
    uint32_t bitrate_bps;
    uint8_t address[5];       /* TX_ADDR = RX_ADDR_P0, LSByte first on SPI */
    uint8_t crc_bytes;
    uint8_t max_len;          /* largest payload (dynamic payload length) */
} nrf24_profile_t;

/* TEAM_250K: SRI/QM/MRM team link: our channel (D-R4), 250 kbps
 * RF_CH 74 = 2474 MHz, 250 kbps, RF_PWR -18 dBm (~+7 dBm at the E01 SMA), patch: 10.0 dBm e.i.r.p. */
static const nrf24_reg_t NRF24_REGS_TEAM_250K[] = {
    {0x01, 0x01},  /* EN_AA */
    {0x02, 0x01},  /* EN_RXADDR */
    {0x03, 0x03},  /* SETUP_AW */
    {0x04, 0x00},  /* SETUP_RETR */
    {0x05, 0x4A},  /* RF_CH */
    {0x06, 0x20},  /* RF_SETUP */
    {0x11, 0x20},  /* RX_PW_P0 */
    {0x1D, 0x05},  /* FEATURE */
    {0x1C, 0x01},  /* DYNPD */
    {0x07, 0x70},  /* STATUS */
    {0x00, 0x0E},  /* CONFIG */
};
static const nrf24_profile_t NRF24_PROFILE_TEAM_250K = {
    "TEAM_250K", NRF24_REGS_TEAM_250K,
    (uint8_t)(sizeof NRF24_REGS_TEAM_250K / sizeof NRF24_REGS_TEAM_250K[0]),
    74u, 250000u, {0xE7, 0xC3, 0x1A, 0x5D, 0x92}, 2u, 32u,
};

/* TEAM_1M: SRI option at 1 Mbps (teams sequential, +18 dB at 70 m)
 * RF_CH 74 = 2474 MHz, 1000 kbps, RF_PWR -18 dBm (~+7 dBm at the E01 SMA), patch: 10.0 dBm e.i.r.p. */
static const nrf24_reg_t NRF24_REGS_TEAM_1M[] = {
    {0x01, 0x01},  /* EN_AA */
    {0x02, 0x01},  /* EN_RXADDR */
    {0x03, 0x03},  /* SETUP_AW */
    {0x04, 0x00},  /* SETUP_RETR */
    {0x05, 0x4A},  /* RF_CH */
    {0x06, 0x00},  /* RF_SETUP */
    {0x11, 0x20},  /* RX_PW_P0 */
    {0x1D, 0x05},  /* FEATURE */
    {0x1C, 0x01},  /* DYNPD */
    {0x07, 0x70},  /* STATUS */
    {0x00, 0x0E},  /* CONFIG */
};
static const nrf24_profile_t NRF24_PROFILE_TEAM_1M = {
    "TEAM_1M", NRF24_REGS_TEAM_1M,
    (uint8_t)(sizeof NRF24_REGS_TEAM_1M / sizeof NRF24_REGS_TEAM_1M[0]),
    74u, 1000000u, {0xE7, 0xC3, 0x1A, 0x5D, 0x92}, 2u, 32u,
};

/* NM_COMMON: PHY shared by all teams in NM (see NM_PHY_PROPOSAL.md)
 * RF_CH 80 = 2480 MHz, 250 kbps, RF_PWR -18 dBm (~+7 dBm at the E01 SMA), omni: 8.0 dBm e.i.r.p. */
static const nrf24_reg_t NRF24_REGS_NM_COMMON[] = {
    {0x01, 0x01},  /* EN_AA */
    {0x02, 0x01},  /* EN_RXADDR */
    {0x03, 0x03},  /* SETUP_AW */
    {0x04, 0x00},  /* SETUP_RETR */
    {0x05, 0x50},  /* RF_CH */
    {0x06, 0x20},  /* RF_SETUP */
    {0x11, 0x20},  /* RX_PW_P0 */
    {0x1D, 0x05},  /* FEATURE */
    {0x1C, 0x01},  /* DYNPD */
    {0x07, 0x70},  /* STATUS */
    {0x00, 0x0E},  /* CONFIG */
};
static const nrf24_profile_t NRF24_PROFILE_NM_COMMON = {
    "NM_COMMON", NRF24_REGS_NM_COMMON,
    (uint8_t)(sizeof NRF24_REGS_NM_COMMON / sizeof NRF24_REGS_NM_COMMON[0]),
    80u, 250000u, {0xC2, 0x5A, 0x9D, 0x3E, 0x71}, 2u, 32u,
};

/* BENCH_WHIP: bench / QM with the 2 dBi whip straight on the SMA (no pad)
 * RF_CH 74 = 2474 MHz, 250 kbps, RF_PWR -18 dBm (~+7 dBm at the E01 SMA), omni: 8.0 dBm e.i.r.p. */
static const nrf24_reg_t NRF24_REGS_BENCH_WHIP[] = {
    {0x01, 0x01},  /* EN_AA */
    {0x02, 0x01},  /* EN_RXADDR */
    {0x03, 0x03},  /* SETUP_AW */
    {0x04, 0x00},  /* SETUP_RETR */
    {0x05, 0x4A},  /* RF_CH */
    {0x06, 0x20},  /* RF_SETUP */
    {0x11, 0x20},  /* RX_PW_P0 */
    {0x1D, 0x05},  /* FEATURE */
    {0x1C, 0x01},  /* DYNPD */
    {0x07, 0x70},  /* STATUS */
    {0x00, 0x0E},  /* CONFIG */
};
static const nrf24_profile_t NRF24_PROFILE_BENCH_WHIP = {
    "BENCH_WHIP", NRF24_REGS_BENCH_WHIP,
    (uint8_t)(sizeof NRF24_REGS_BENCH_WHIP / sizeof NRF24_REGS_BENCH_WHIP[0]),
    74u, 250000u, {0xE7, 0xC3, 0x1A, 0x5D, 0x92}, 2u, 32u,
};

#endif /* NRF24_CONFIG_H */
