/* MTP-F26 Team C - portable nRF24L01+ packet driver (Ebyte E01-ML01DP5).
 *
 * Micro-agnostic: the board supplies an nrf24_hal_t (SPI mode 0, <= 10 MHz, CSN,
 * CE, delays, microsecond clock). Register profiles come from nrf24_config.h,
 * generated by radio/phy_config.py.
 *
 * Frames use dynamic payload length (1..32 B) and the radio's CRC-16. Every
 * frame is sent with W_TX_PAYLOAD_NOACK: no Enhanced-ShockBurst ACKs or retries
 * on air, so our own ARQ (proto/src/link.c) stays in charge and other teams'
 * radios can share the NM channel. The E01 module switches its PA/LNA from the
 * chip itself, so the MCU only needs SPI + CSN + CE (+ IRQ, optional: polling
 * works without it).
 */
#ifndef NRF24_H
#define NRF24_H

#include <stdint.h>

#include "nrf24_config.h"

#define NRF24_MAX_PAYLOAD 32u
#define NRF24_MAX_LEGAL_CH 83u    /* 2483 MHz: CNAF UN-85 ends at 2483.5 MHz */
#define NRF24_TX_SETTLE_US 130u   /* PLL settling, standby -> TX/RX (PS v1.0, Tstby2a) */

typedef struct {
    void *ctx;
    void (*select)(void *ctx, int active);   /* active=1 drives CSN low */
    uint8_t (*transfer)(void *ctx, uint8_t out);
    void (*ce)(void *ctx, int high);
    void (*delay_us)(void *ctx, uint32_t us);
    uint32_t (*micros)(void *ctx);
} nrf24_hal_t;

typedef enum {
    NRF24_OK = 0,
    NRF24_ERR_SPI,       /* write/read-back test failed: wiring or CSN */
    NRF24_ERR_NOT_PLUS,  /* RF_DR_LOW does not stick: nRF24L01 (non-plus), no 250 kbps */
    NRF24_ERR_TIMEOUT,
    NRF24_ERR_LEN,
    NRF24_ERR_CH,
    NRF24_ERR_NODATA,
} nrf24_status_t;

typedef struct {
    const nrf24_hal_t *hal;
    const nrf24_profile_t *profile;
    uint8_t rf_ch;
    uint8_t rx_on;
    uint8_t last_rpd;    /* RPD after the last frame: 1 = above -64 dBm at the chip */
} nrf24_t;

nrf24_status_t nrf24_init(nrf24_t *dev, const nrf24_hal_t *hal, const nrf24_profile_t *profile);
nrf24_status_t nrf24_set_channel(nrf24_t *dev, uint8_t rf_ch);

/* Blocking send of one frame; leaves the radio in standby (RX off). */
nrf24_status_t nrf24_send(nrf24_t *dev, const uint8_t *body, uint8_t len);

/* Enter RX, then call nrf24_poll_rx until it returns NRF24_OK. The radio drops
 * frames that fail CRC, so only good frames reach the 3-deep RX FIFO. */
nrf24_status_t nrf24_start_rx(nrf24_t *dev);
nrf24_status_t nrf24_poll_rx(nrf24_t *dev, uint8_t *body, uint8_t *len);

/* Carrier detect on the current channel: 1 if the received power is above
 * -64 dBm at the chip (~-76 dBm at the E01 antenna port, LNA ~12 dB). Needs RX on
 * for >= 170 us. Used for the channel survey and listen-before-talk. */
int nrf24_carrier(nrf24_t *dev);

/* On-air time of one frame with a len-byte payload, in microseconds (no settling). */
uint32_t nrf24_airtime_us(const nrf24_profile_t *p, uint8_t len);

uint8_t nrf24_read_reg(nrf24_t *dev, uint8_t addr);
void nrf24_write_reg(nrf24_t *dev, uint8_t addr, uint8_t value);

#endif /* NRF24_H */
