/* MTP-F26 Team C - portable RFM69HCW (SX1231) packet driver.
 *
 * Micro-agnostic: the board supplies an rfm69_hal_t (SPI mode 0, <= 10 MHz,
 * NSS, RESET, delays, millisecond clock). Register profiles come from
 * rfm69_config.h, generated by radio/phy_config.py.
 *
 * Frames are SX1231 variable-length packets: [length][body...][CRC if hw_crc].
 * One frame fits the 66 B FIFO (body <= profile->max_len <= 64 B), so no FIFO
 * refill is needed. Polling only; DIO0 is mapped (PacketSent in TX,
 * PayloadReady in RX) so a board can switch to interrupts later.
 */
#ifndef RFM69_H
#define RFM69_H

#include <stdint.h>

#include "dc_guard.h"
#include "rfm69_config.h"

#define RFM69_VERSION 0x24u
#define RFM69_FIFO_SIZE 66u

typedef struct {
    void *ctx;
    void (*select)(void *ctx, int active);     /* active=1 drives NSS low */
    uint8_t (*transfer)(void *ctx, uint8_t out);
    void (*reset)(void *ctx, int high);        /* RFM69 RESET is active HIGH */
    void (*delay_ms)(void *ctx, uint32_t ms);
    uint32_t (*millis)(void *ctx);
} rfm69_hal_t;

typedef enum {
    RFM69_MODE_SLEEP = 0,
    RFM69_MODE_STDBY = 1,
    RFM69_MODE_FS = 2,
    RFM69_MODE_TX = 3,
    RFM69_MODE_RX = 4,
} rfm69_mode_t;

typedef enum {
    RFM69_OK = 0,
    RFM69_ERR_SPI,      /* SPI write/read-back test failed: wiring or NSS */
    RFM69_ERR_VERSION,  /* RegVersion != 0x24: not an SX1231/RFM69 */
    RFM69_ERR_TIMEOUT,
    RFM69_ERR_LEN,
    RFM69_ERR_DUTY,     /* frame would exceed the duty-cycle budget */
    RFM69_ERR_NODATA,
} rfm69_status_t;

typedef struct {
    const rfm69_hal_t *hal;
    const rfm69_profile_t *profile;
    dc_guard_t *guard;          /* NULL: no duty-cycle enforcement (bench band) */
    rfm69_mode_t mode;
    int16_t last_rssi_x2;       /* RSSI of the last frame, in 0.5 dBm units */
} rfm69_t;

rfm69_status_t rfm69_init(rfm69_t *dev, const rfm69_hal_t *hal,
                          const rfm69_profile_t *profile, dc_guard_t *guard);
rfm69_status_t rfm69_set_mode(rfm69_t *dev, rfm69_mode_t mode);

/* Blocking send of one frame; returns to standby. */
rfm69_status_t rfm69_send(rfm69_t *dev, const uint8_t *body, uint8_t len);

/* Enter RX, then call rfm69_poll_rx until it returns RFM69_OK. With hw_crc the
 * radio drops frames that fail CRC, so only good frames reach the FIFO. */
rfm69_status_t rfm69_start_rx(rfm69_t *dev);
rfm69_status_t rfm69_poll_rx(rfm69_t *dev, uint8_t *body, uint8_t *len);

/* On-air time of one frame with a body of len bytes, in microseconds. */
uint32_t rfm69_airtime_us(const rfm69_profile_t *p, uint8_t len);

uint8_t rfm69_read_reg(rfm69_t *dev, uint8_t addr);
void rfm69_write_reg(rfm69_t *dev, uint8_t addr, uint8_t value);

#endif /* RFM69_H */
