/* GENERATED by radio/phy_config.py - do not edit by hand. */
#ifndef RFM69_CONFIG_H
#define RFM69_CONFIG_H

#include <stdint.h>

typedef struct { uint8_t addr; uint8_t value; } rfm69_reg_t;

typedef struct {
    const char *name;
    const rfm69_reg_t *regs;
    uint8_t n_regs;
    uint32_t bitrate_bps;    /* actual, after register quantisation */
    uint8_t preamble_bytes;
    uint8_t sync_bytes;
    uint8_t hw_crc;          /* 1: radio appends/checks CRC-16 (2 B on air) */
    uint8_t max_len;         /* largest length-byte value accepted */
} rfm69_profile_t;

/* SRI_100K: SRI/QM/MRM team-internal link: 10 000 lines in 2 min
 * 869.525024 MHz, 100.000 kbps, Fdev 49.988 kHz, BT0.5, beta 1.00, RxBw 166.7 kHz, PA +17 dBm */
static const rfm69_reg_t RFM69_REGS_SRI_100K[] = {
    {0x01, 0x04},  /* OPMODE */
    {0x02, 0x02},  /* DATAMODUL */
    {0x03, 0x01},  /* BITRATEMSB */
    {0x04, 0x40},  /* BITRATELSB */
    {0x05, 0x03},  /* FDEVMSB */
    {0x06, 0x33},  /* FDEVLSB */
    {0x07, 0xD9},  /* FRFMSB */
    {0x08, 0x61},  /* FRFMID */
    {0x09, 0x9A},  /* FRFLSB */
    {0x11, 0x7F},  /* PALEVEL */
    {0x13, 0x1A},  /* OCP */
    {0x19, 0x51},  /* RXBW */
    {0x1A, 0x91},  /* AFCBW */
    {0x1E, 0x00},  /* AFCFEI */
    {0x29, 0xE4},  /* RSSITHRESH */
    {0x2C, 0x00},  /* PREAMBLEMSB */
    {0x2D, 0x04},  /* PREAMBLELSB */
    {0x2E, 0x88},  /* SYNCCONFIG */
    {0x2F, 0x6C},  /* SYNCVALUE1 */
    {0x30, 0xA3},  /* SYNCVALUE2 */
    {0x37, 0xD0},  /* PACKETCONFIG1 */
    {0x38, 0x40},  /* PAYLOADLENGTH */
    {0x3C, 0x8F},  /* FIFOTHRESH */
    {0x3D, 0x02},  /* PACKETCONFIG2 */
    {0x5A, 0x55},  /* TESTPA1 */
    {0x5C, 0x70},  /* TESTPA2 */
    {0x6F, 0x30},  /* TESTDAGC */
};
static const rfm69_profile_t RFM69_PROFILE_SRI_100K = {
    "SRI_100K", RFM69_REGS_SRI_100K,
    (uint8_t)(sizeof RFM69_REGS_SRI_100K / sizeof RFM69_REGS_SRI_100K[0]),
    100000u, 4u, 2u, 1u, 64u,
};

/* ROBUST_38K4: fallback when 100 kbps fails on campus (+5 dB sensitivity)
 * 869.525024 MHz, 38.415 kbps, Fdev 38.391 kHz, BT0.5, beta 2.00, RxBw 100.0 kHz, PA +17 dBm */
static const rfm69_reg_t RFM69_REGS_ROBUST_38K4[] = {
    {0x01, 0x04},  /* OPMODE */
    {0x02, 0x02},  /* DATAMODUL */
    {0x03, 0x03},  /* BITRATEMSB */
    {0x04, 0x41},  /* BITRATELSB */
    {0x05, 0x02},  /* FDEVMSB */
    {0x06, 0x75},  /* FDEVLSB */
    {0x07, 0xD9},  /* FRFMSB */
    {0x08, 0x61},  /* FRFMID */
    {0x09, 0x9A},  /* FRFLSB */
    {0x11, 0x7F},  /* PALEVEL */
    {0x13, 0x1A},  /* OCP */
    {0x19, 0x4A},  /* RXBW */
    {0x1A, 0x8A},  /* AFCBW */
    {0x1E, 0x00},  /* AFCFEI */
    {0x29, 0xE4},  /* RSSITHRESH */
    {0x2C, 0x00},  /* PREAMBLEMSB */
    {0x2D, 0x04},  /* PREAMBLELSB */
    {0x2E, 0x88},  /* SYNCCONFIG */
    {0x2F, 0x6C},  /* SYNCVALUE1 */
    {0x30, 0xA3},  /* SYNCVALUE2 */
    {0x37, 0xD0},  /* PACKETCONFIG1 */
    {0x38, 0x40},  /* PAYLOADLENGTH */
    {0x3C, 0x8F},  /* FIFOTHRESH */
    {0x3D, 0x02},  /* PACKETCONFIG2 */
    {0x5A, 0x55},  /* TESTPA1 */
    {0x5C, 0x70},  /* TESTPA2 */
    {0x6F, 0x30},  /* TESTDAGC */
};
static const rfm69_profile_t RFM69_PROFILE_ROBUST_38K4 = {
    "ROBUST_38K4", RFM69_REGS_ROBUST_38K4,
    (uint8_t)(sizeof RFM69_REGS_ROBUST_38K4 / sizeof RFM69_REGS_ROBUST_38K4[0]),
    38415u, 4u, 2u, 1u, 64u,
};

/* NM_COMMON: draft PHY shared by all teams in NM (see nm_phy_proposal.md)
 * 869.525024 MHz, 100.000 kbps, Fdev 49.988 kHz, BT0.5, beta 1.00, RxBw 166.7 kHz, PA +17 dBm */
static const rfm69_reg_t RFM69_REGS_NM_COMMON[] = {
    {0x01, 0x04},  /* OPMODE */
    {0x02, 0x02},  /* DATAMODUL */
    {0x03, 0x01},  /* BITRATEMSB */
    {0x04, 0x40},  /* BITRATELSB */
    {0x05, 0x03},  /* FDEVMSB */
    {0x06, 0x33},  /* FDEVLSB */
    {0x07, 0xD9},  /* FRFMSB */
    {0x08, 0x61},  /* FRFMID */
    {0x09, 0x9A},  /* FRFLSB */
    {0x11, 0x7F},  /* PALEVEL */
    {0x13, 0x1A},  /* OCP */
    {0x19, 0x51},  /* RXBW */
    {0x1A, 0x91},  /* AFCBW */
    {0x1E, 0x00},  /* AFCFEI */
    {0x29, 0xE4},  /* RSSITHRESH */
    {0x2C, 0x00},  /* PREAMBLEMSB */
    {0x2D, 0x04},  /* PREAMBLELSB */
    {0x2E, 0x88},  /* SYNCCONFIG */
    {0x2F, 0x2D},  /* SYNCVALUE1 */
    {0x30, 0xD4},  /* SYNCVALUE2 */
    {0x37, 0x80},  /* PACKETCONFIG1 */
    {0x38, 0x40},  /* PAYLOADLENGTH */
    {0x3C, 0x8F},  /* FIFOTHRESH */
    {0x3D, 0x02},  /* PACKETCONFIG2 */
    {0x5A, 0x55},  /* TESTPA1 */
    {0x5C, 0x70},  /* TESTPA2 */
    {0x6F, 0x30},  /* TESTDAGC */
};
static const rfm69_profile_t RFM69_PROFILE_NM_COMMON = {
    "NM_COMMON", RFM69_REGS_NM_COMMON,
    (uint8_t)(sizeof RFM69_REGS_NM_COMMON / sizeof RFM69_REGS_NM_COMMON[0]),
    100000u, 4u, 2u, 0u, 64u,
};

/* BENCH_5MW: bench and repeated campus tests: 869.85 MHz, 5 mW e.r.p., no duty-cycle limit
 * 869.849976 MHz, 100.000 kbps, Fdev 49.988 kHz, BT0.5, beta 1.00, RxBw 166.7 kHz, PA +9 dBm */
static const rfm69_reg_t RFM69_REGS_BENCH_5MW[] = {
    {0x01, 0x04},  /* OPMODE */
    {0x02, 0x02},  /* DATAMODUL */
    {0x03, 0x01},  /* BITRATEMSB */
    {0x04, 0x40},  /* BITRATELSB */
    {0x05, 0x03},  /* FDEVMSB */
    {0x06, 0x33},  /* FDEVLSB */
    {0x07, 0xD9},  /* FRFMSB */
    {0x08, 0x76},  /* FRFMID */
    {0x09, 0x66},  /* FRFLSB */
    {0x11, 0x77},  /* PALEVEL */
    {0x13, 0x1A},  /* OCP */
    {0x19, 0x51},  /* RXBW */
    {0x1A, 0x91},  /* AFCBW */
    {0x1E, 0x00},  /* AFCFEI */
    {0x29, 0xE4},  /* RSSITHRESH */
    {0x2C, 0x00},  /* PREAMBLEMSB */
    {0x2D, 0x04},  /* PREAMBLELSB */
    {0x2E, 0x88},  /* SYNCCONFIG */
    {0x2F, 0x6C},  /* SYNCVALUE1 */
    {0x30, 0xA3},  /* SYNCVALUE2 */
    {0x37, 0xD0},  /* PACKETCONFIG1 */
    {0x38, 0x40},  /* PAYLOADLENGTH */
    {0x3C, 0x8F},  /* FIFOTHRESH */
    {0x3D, 0x02},  /* PACKETCONFIG2 */
    {0x5A, 0x55},  /* TESTPA1 */
    {0x5C, 0x70},  /* TESTPA2 */
    {0x6F, 0x30},  /* TESTDAGC */
};
static const rfm69_profile_t RFM69_PROFILE_BENCH_5MW = {
    "BENCH_5MW", RFM69_REGS_BENCH_5MW,
    (uint8_t)(sizeof RFM69_REGS_BENCH_5MW / sizeof RFM69_REGS_BENCH_5MW[0]),
    100000u, 4u, 2u, 1u, 64u,
};

#endif /* RFM69_CONFIG_H */
